server:
  port: 3600
  servlet:
    context-path: /bootcamp

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jce82fa3b6862d07cf64b390a84eee4e0e3bb57cc208ee4baaa7a251ef720ac8c
    username: bgnlwwvbywgbti
    password: ce82fa3b6862d07cf64b390a84eee4e0e3bb57cc208ee4baaa7a251ef720ac8c
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none

application:
  description: Projeto criado para a Dev Week Santander